# Generated by Django 5.2 on 2025-04-26 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=255, verbose_name='место')),
                ('time', models.TimeField(verbose_name='время')),
                ('action_habit', models.CharField(max_length=255, verbose_name='действие')),
                ('pleasant_habit', models.BooleanField(verbose_name='приятная привычка')),
                ('frequency', models.CharField(choices=[('3 days', 'Каждые 3 дня'), ('weekly', 'Каждую неделю'), ('daily', 'Каждый день')], default='daily', max_length=30, verbose_name='частота')),
                ('reward', models.CharField(blank=True, max_length=255, null=True, verbose_name='вознагрождение')),
                ('time_to_do', models.DurationField(verbose_name='время на выполнение')),
                ('is_public', models.BooleanField(default=False, verbose_name='публичность')),
                ('related_habit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related', to='habits.habit', verbose_name='связанная привычка')),
            ],
        ),
    ]
